export const actionIds = {
  appSidebarToggle: "app.sidebar.toggle",
  navCharacters: "nav.characters",
  navEffects: "nav.effects",
  navItems: "nav.items",
  navMaps: "nav.maps",
  navBuildings: "nav.buildings",
  characterExportGltf: "character.export.gltf",
  characterImportGltf: "character.import.gltf",
  itemExportGltf: "item.export.gltf",
  itemImportGltf: "item.import.gltf",
  itemWorkbenchSave: "item.workbench.save",
  mapExportGltf: "map.export.gltf",
  mapToggleObjectMarkers: "map.view.toggleObjectMarkers",
  mapToggleWireframe: "map.view.toggleWireframe",
  buildingExportGltf: "building.export.gltf",
  buildingToggleMeshOutlines: "building.view.toggleMeshOutlines",
  buildingToggleAnimation: "building.view.toggleAnimation",
  buildingToggleMetadata: "building.view.toggleMetadata",
  effectSave: "effect.save",
  effectUndo: "effect.undo",
  effectRedo: "effect.redo",
  effectGizmoTranslate: "effect.gizmo.translate",
  effectGizmoRotate: "effect.gizmo.rotate",
  effectGizmoScale: "effect.gizmo.scale",
  effectGizmoOff: "effect.gizmo.off",
  effectToggleCompositePreview: "effect.preview.toggleComposite",
  effectKeyframeCopy: "effect.keyframe.copy",
  effectKeyframePaste: "effect.keyframe.paste",
  commandPaletteOpen: "app.palette.open",
} as const;

export type ActionId = (typeof actionIds)[keyof typeof actionIds];
